using System.ClientModel;
using Azure.AI.OpenAI;
using Microsoft.Extensions.Logging;
using OpenAI.Chat;

namespace Platform.Intelligence.Reasoning;

public sealed class AzureOpenAIReasoningEngineOptions
{
    public required string Endpoint { get; init; }
    public required string ApiKey { get; init; }
    public required string DeploymentName { get; init; }
}

public sealed class AzureOpenAIReasoningEngine : IReasoningEngine
{
    private readonly ChatClient _chatClient;
    private readonly ILogger<AzureOpenAIReasoningEngine> _logger;

    public AzureOpenAIReasoningEngine(AzureOpenAIReasoningEngineOptions options, ILogger<AzureOpenAIReasoningEngine> logger)
    {
        _logger = logger;
        var client = new AzureOpenAIClient(new Uri(options.Endpoint), new ApiKeyCredential(options.ApiKey));
        _chatClient = client.GetChatClient(options.DeploymentName);
    }

    public async Task<ReasoningResult> AnalyzeAsync(ReasoningRequest request, CancellationToken ct = default)
    {
        _logger.LogInformation("Sending reasoning request to Azure OpenAI: {PromptLength} chars", request.Prompt.Length);

        try
        {
            var messages = new List<ChatMessage>();

            if (!string.IsNullOrEmpty(request.SystemInstruction))
                messages.Add(ChatMessage.CreateSystemMessage(request.SystemInstruction));

            var userContent = $"Context:\n{request.Context}\n\nRequest:\n{request.Prompt}";
            if (request.Parameters.Count > 0)
            {
                userContent += "\n\nParameters:\n";
                foreach (var kvp in request.Parameters)
                    userContent += $"- {kvp.Key}: {kvp.Value}\n";
            }

            messages.Add(ChatMessage.CreateUserMessage(userContent));

            var options = new ChatCompletionOptions
            {
                Temperature = (float)request.Temperature,
                MaxOutputTokenCount = request.MaxTokens
            };

            var response = await _chatClient.CompleteChatAsync(messages, options, ct);
            var completion = response.Value;

            var responseText = completion.Content[0].Text;
            var tokensUsed = completion.Usage.TotalTokenCount;

            _logger.LogInformation("Azure OpenAI response received: {TokensUsed} tokens", tokensUsed);

            return new ReasoningResult
            {
                Succeeded = true,
                Response = responseText,
                Confidence = 0.85,
                Reasoning = $"Generated by Azure OpenAI ({tokensUsed} tokens)",
                TokensUsed = tokensUsed
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Azure OpenAI reasoning request failed");

            return new ReasoningResult
            {
                Succeeded = false,
                Response = string.Empty,
                Confidence = 0.0,
                Reasoning = $"Failed: {ex.Message}"
            };
        }
    }
}